Allowing some 3D tools to stretch to the dimensions of their container.
vertigis/vertigis-web-incubator pull request #13
Opened 2023-11-30 22:37 UTC by eric-parsons

Some minor styling changes to allow the shadow cast tool to stretch to its container's size. It was working previously only by accident because Esri's CSS had "width: 200" which is invalid. They changed it in 4.28 to "width: 200px" which made it much smaller and hard to use.

I also updated some packages to fix audit issues.

2023-12-01 02:57 UTC, scottander approved these changes

2023-12-01 22:44 UTC, edorableraf requested changes
Looks like the Slice component has some sizing issues:
![image](https://github.com/vertigis/vertigis-web-incubator/assets/55640599/26cefdb7-a333-423c-b7eb-b15480d7f0f9)

Compared to the Line of Sight tool:
![image](https://github.com/vertigis/vertigis-web-incubator/assets/55640599/be4e42b1-e668-42ac-b0b6-9a27f43c9a89)

2023-12-04 17:04 UTC, eric-parsons commented
> Looks like the Slice component has some sizing issues...

@edorableraf, those issues should be fixed now by my latest update. @scottander, please have a look at the changes when you have a sec.

2023-12-04 18:00 UTC, edorableraf commented
@eric-parsons Looks good. One styling nitpick that I missed from last time, but probably OK to merge with or without a fix.

Font colour for the elevation profile layers is hard to read in dark mode:
![image](https://github.com/vertigis/vertigis-web-incubator/assets/55640599/f4f8c7bf-4a55-46e2-8f3f-9d8fe3222a0b)

2023-12-04 18:02 UTC, edorableraf approved these changes

2023-12-04 19:56 UTC, eric-parsons commented
Odd, it looks fine to me, both in preview and local:

<img width="349" alt="image" src="https://github.com/vertigis/vertigis-web-incubator/assets/4603335/591ee910-4e49-4827-ae88-dbe77599a004">

Both in Brave and Firefox 🤷. It's either a caching issue or some strange OS issue.

2023-12-04 20:17 UTC, scottander commented
> > Looks like the Slice component has some sizing issues...
> 
> @edorableraf, those issues should be fixed now by my latest update. @scottander, please have a look at the changes when you have a sec.

Looks good to me.

2023-12-04 21:22 UTC, edorableraf commented
I checked again and it looks fine now. Not sure what was the cause, but we're probably good to go.

> Both in Brave and Firefox 🤷. It's either a caching issue or some strange OS issue.

2023-12-04 22:28 UTC, merged